# Generated by Django 5.1.4 on 2024-12-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryimage',
            name='username',
            field=models.CharField(default='default_user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
