# Generated by Django 5.1.4 on 2024-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_alter_diaryimage_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='consolation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='emotions_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
