# Generated by Django 5.1.4 on 2024-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_remove_diaryimage_ai_analyze_remove_diaryimage_diary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='ymd',
            field=models.DateField(),
        ),
    ]
