# Generated by Django 5.1.4 on 2024-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0009_alter_diaryimage_ymd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='ymd',
            field=models.DateTimeField(),
        ),
    ]
