# Generated by Django 5.1.4 on 2024-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0011_alter_diary_ymd'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='max_mood',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='weekly_mood',
            field=models.TextField(blank=True, null=True),
        ),
    ]
