# Generated by Django 5.1.4 on 2024-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0012_statistics_max_mood_statistics_weekly_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='ymd',
            new_name='week_start',
        ),
    ]
